### ISSUE TITLE
[RFE] Add Mosh UDP service port and ingress

### ISSUE THREAD

**Issue by usrbinkat** [ContainerCraft/helm#25]
# Problem
Konductor image added Mosh mobile shell server for better remote shell experience. Currently this enhanced shell is not exposed as a service by the helm chart and there is no ingress definition for it.

# Solution

Add mosh shell support
- [ ] udp service
- [ ] udp ingress
- [ ] documentation

## Example

Mosh connection command
```bash
mosh --ssh="ssh -p 31743" --server "LANG=en_US.UTF-8 mosh-server new -p 32767 -i 0.0.0.0" k@192.168.1.21
```

Example working service definition
```yaml
apiVersion: v1
kind: Service
metadata:
  name: konductor
  labels:
    app: konductor
    app.kubernetes.io/instance: k
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: konductor
    app.kubernetes.io/version: 0.0.3
    helm.sh/chart: konductor-0.0.3
spec:
  ports:
  - port: 32767
    protocol: UDP
    targetPort: 32767
    nodePort: 32767
  selector:
    app.kubernetes.io/instance: k
    app.kubernetes.io/name: konductor
  type: NodePort
```
